name: Java CI

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11

      - name: Test
        run: gradle build test

#      - name: Sonar
#        continue-on-error: true
#        run: gradle sonar -Dsonar.plugins.downloadOnlyRequired=true -Dsonar.host.url=http://v2202402203466256255.megasrv.de/sonar -Dsonar.token=${{ secrets.SONAR_USER_TOKEN }}

      - name: Archive SBOM
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: build/resources/main/META-INF/sbom/application.cdx.json

